### ISSUE TITLE
highlight-indentation  error

### ISSUE THREAD

**Issue by yaolindlut** [yangwen0228/unimacs#1]
when i enter the python-mode, an error was occured: "Error (use-package): elpy :init: Required feature ‘highlight-indentation’ was not provided"

**Comment by yangwen0228** [comment]
No errors reproduced! Please use "M-x" `unimacs-recompile-user-files' and "C-u" to recompile the configuration files!

**Comment by yaolindlut** [comment]
hasn't been recomplied like a thousands time, it doesn't work!
