### ISSUE TITLE
use-package in java-mode

### ISSUE THREAD

**Issue by ShuZhong** [yangwen0228/unimacs#4]
**Location:** init-java.el
The emacs don't have a package which name is _**java-mode**_.

In `(use-package java-mode)`, the code after `:config XXXX` will not be run.
Although you add a `:ensure nil` to prohabit error.

Maybe should change to `(use-package cc-mode)`,because the _**java-mode**_ origin from package _**cc-mode**_

**Comment by yangwen0228** [comment]
Yes, you are right. I've already fixed this error.
